export interface ProductItem {
  id: number | string;
  name: string;
  subTitle?: string;
  category: string;
  line: string;
  concern: string;
  price: number;
  originalPrice?: number;
  priceFormatted: string;
  originalPriceFormatted?: string;
  tag?: string;
  discountBadge?: string;
  rating: number;
  reviewsCount: number;
  image: string;
  inStock: boolean;
}

export const ALL_PRODUCTS: ProductItem[] = [
  {
    id: 101,
    name: "D'LEXO Collagen Sil Booster Ampoule 70mg*4ea+35ml",
    subTitle: 'PDRN Solution Collagen Booster Ampoule 35ml',
    category: 'Special Ampoule',
    line: 'Tension Master Series',
    concern: 'Lifting & Elasticity',
    price: 36.23,
    originalPrice: 172.46,
    priceFormatted: '$36.23',
    originalPriceFormatted: '$172.46',
    tag: 'NEW',
    discountBadge: 'SAVE 78%',
    rating: 4.9,
    reviewsCount: 128,
    image: 'https://en.dermaline.co.kr/web/upload/category/editor/2024/12/02/9f3e225d8efe11d4977e6a1af0a1e1dc.jpg',
    inStock: true,
  },
  {
    id: 102,
    name: "D'LEXO Tension Master Real Lifting Ampoule 35ml",
    subTitle: 'High-Purity Bio-Lifting Peptide Solution',
    category: 'Lifting Thread',
    line: 'Tension Master Series',
    concern: 'Lifting & Elasticity',
    price: 38.5,
    originalPrice: 45.0,
    priceFormatted: '$38.50',
    originalPriceFormatted: '$45.00',
    tag: 'NEW',
    discountBadge: 'SAVE 14%',
    rating: 4.9,
    reviewsCount: 86,
    image: 'https://en.dermaline.co.kr/web/upload/category/editor/2024/12/02/9525cceae1c70e30eb49a888bdf218cf.jpg',
    inStock: true,
  },
  {
    id: 103,
    name: "D'LEXO Exo-Peptide Bio-Booster Solution 50ml",
    subTitle: '10 Billion Plant Exosome Cellular Complex',
    category: 'Exo-Peptide',
    line: 'Cellular Bio-Booster',
    concern: 'Skin Recovery',
    price: 54.0,
    originalPrice: 65.0,
    priceFormatted: '$54.00',
    originalPriceFormatted: '$65.00',
    tag: 'BESTSELLER',
    discountBadge: 'SAVE 17%',
    rating: 5.0,
    reviewsCount: 210,
    image: 'https://en.dermaline.co.kr/web/upload/category/editor/2024/12/02/7cf511574fe469cd67cd938c532abd20.jpg',
    inStock: true,
  },
  {
    id: 104,
    name: 'PDX5 Skin Booster Total Solution 5ml*5vial',
    subTitle: 'Improvement of elasticity + Barrier Reinforcement',
    category: 'Special Ampoule',
    line: 'Cellular Bio-Booster',
    concern: 'Barrier Repair',
    price: 179.71,
    originalPrice: 240.0,
    priceFormatted: '$179.71',
    originalPriceFormatted: '$240.00',
    tag: 'HOSPITAL PROVEN',
    discountBadge: 'SAVE 25%',
    rating: 5.0,
    reviewsCount: 94,
    image: 'https://en.dermaline.co.kr/web/product/big/202603/7a7bef14e32eecfd07cd0508b6be29f5.jpg',
    inStock: true,
  },
  {
    id: 105,
    name: 'Derma Solution PDRN Magic Ampoule 5ml*7ea',
    subTitle: 'High-Purified Salmon PDRN Tissue Regenerator',
    category: 'Cellular Bio-Booster',
    line: 'Exo-Peptide Series',
    concern: 'Skin Recovery',
    price: 108.7,
    originalPrice: 150.0,
    priceFormatted: '$108.70',
    originalPriceFormatted: '$150.00',
    tag: '99.5% PDRN',
    discountBadge: 'SAVE 28%',
    rating: 4.8,
    reviewsCount: 156,
    image: 'https://en.dermaline.co.kr/web/product/big/202606/3a5b6c05e37530bd4f1ffbcd888ec38d.jpg',
    inStock: true,
  },
  {
    id: 106,
    name: "D'LEXO NAD Power Solution Ampoule 35ml",
    subTitle: 'High-purity cellular NAD anti-aging solution',
    category: 'Special Ampoule',
    line: 'Tension Master Series',
    concern: 'Lifting & Elasticity',
    price: 35.21,
    originalPrice: 42.0,
    priceFormatted: '$35.21',
    originalPriceFormatted: '$42.00',
    tag: 'NEW',
    discountBadge: 'SAVE 16%',
    rating: 4.9,
    reviewsCount: 112,
    image: 'https://en.dermaline.co.kr/web/upload/category/editor/2024/12/02/7cf511574fe469cd67cd938c532abd20.jpg',
    inStock: true,
  },
  {
    id: 107,
    name: "D'LEXO Aqua Vita Solution Cream 100g",
    subTitle: '8-Layer Hyaluronic Acid Deep Hydration Lock',
    category: 'Cosmeceuticals',
    line: 'Cellular Bio-Booster',
    concern: 'Deep Hydration',
    price: 42.0,
    originalPrice: 48.0,
    priceFormatted: '$42.00',
    originalPriceFormatted: '$48.00',
    tag: 'BESTSELLER',
    discountBadge: 'SAVE 12%',
    rating: 4.9,
    reviewsCount: 145,
    image: '/images/hero/hero_studio_1.jpg',
    inStock: true,
  },
  {
    id: 108,
    name: 'Bio-Cellulose Deep Hydrating Mask Box (10 Sheets)',
    subTitle: '100% Coconut Bio-Cellulose Hydro-Gel Sheet',
    category: 'Cosmeceuticals',
    line: 'Exo-Peptide Series',
    concern: 'Deep Hydration',
    price: 35.0,
    originalPrice: 40.0,
    priceFormatted: '$35.00',
    originalPriceFormatted: '$40.00',
    tag: 'MASK SET',
    discountBadge: 'SAVE 12%',
    rating: 4.8,
    reviewsCount: 98,
    image: '/images/hero/hero_studio_3.jpg',
    inStock: true,
  },
  {
    id: 109,
    name: 'Exo-Peptide Barrier Recovery Cream 80ml',
    subTitle: '5-Ceramide Lipid Matrix Barrier Shield',
    category: 'Barrier Care',
    line: 'Exo-Peptide Series',
    concern: 'Barrier Repair',
    price: 52.0,
    originalPrice: 60.0,
    priceFormatted: '$52.00',
    originalPriceFormatted: '$60.00',
    tag: 'BARRIER SHIELD',
    discountBadge: 'SAVE 13%',
    rating: 5.0,
    reviewsCount: 184,
    image: '/images/hero/hero_studio_2.jpg',
    inStock: true,
  },
  {
    id: 110,
    name: 'DermaVline Master Lifting Thread Set (4x10 Threads)',
    subTitle: 'Hospital Grade Polydioxanone Biocompatible Threads',
    category: 'Lifting Thread',
    line: 'Tension Master Series',
    concern: 'Lifting & Elasticity',
    price: 165.0,
    originalPrice: 195.0,
    priceFormatted: '$165.00',
    originalPriceFormatted: '$195.00',
    tag: 'CLINICAL THREAD',
    discountBadge: 'SAVE 15%',
    rating: 5.0,
    reviewsCount: 76,
    image: 'https://en.dermaline.co.kr/web/upload/category/editor/2024/12/02/9525cceae1c70e30eb49a888bdf218cf.jpg',
    inStock: true,
  },
  {
    id: 111,
    name: 'Exo-Cellular Brightening & Radiance Serum 35ml',
    subTitle: 'Niacinamide 5% & Glutathione Bio-Booster',
    category: 'Exo-Peptide',
    line: 'Cellular Bio-Booster',
    concern: 'Brightening',
    price: 46.0,
    originalPrice: 52.0,
    priceFormatted: '$46.00',
    originalPriceFormatted: '$52.00',
    tag: 'RADIANCE',
    discountBadge: 'SAVE 11%',
    rating: 4.8,
    reviewsCount: 62,
    image: '/images/hero/hero_korean_model_2.jpg',
    inStock: true,
  },
  {
    id: 112,
    name: 'PDRN Intensive Lip & Eye Contour Balm 15g',
    subTitle: 'Concentrated Salmon PDRN Fine Line Smooth Balm',
    category: 'Cosmeceuticals',
    line: 'Tension Master Series',
    concern: 'Skin Recovery',
    price: 29.0,
    originalPrice: 34.0,
    priceFormatted: '$29.00',
    originalPriceFormatted: '$34.00',
    tag: 'CONTOUR CARE',
    discountBadge: 'SAVE 14%',
    rating: 4.7,
    reviewsCount: 54,
    image: '/images/hero/hero_korean_model_3.jpg',
    inStock: true,
  },
];
