import { ProductItem } from '@/types/product';

export const MOCK_PRODUCTS: ProductItem[] = [
  // 1. PDRN & D'LEXO Line
  {
    id: 'p-1',
    name: "D'LEXO Collagen Sil Booster Ampoule 70mg*4ea+35ml",
    subtitle: 'PDRN Solution Collagen Booster Ampoule 35ml',
    subTitle: 'PDRN Solution Collagen Booster Ampoule 35ml',
    slug: 'dlexo-collagen-sil-booster-ampoule',
    category: 'SPECIAL AMPOULE',
    line: 'Special Ampoule Care',
    lineSlug: 'special-ampoule-care',
    type: 'Special Ampoule',
    typeSlug: 'special-ampoule',
    brand: 'DLEXO',
    brandSlug: 'dlexo',
    concern: 'Anti-Aging & Elasticity',
    price: 36.23,
    originalPrice: 172.46,
    rating: 4.9,
    reviewCount: 128,
    reviewsCount: 128,
    image: 'https://en.dermaline.co.kr/web/upload/category/editor/2024/12/02/9f3e225d8efe11d4977e6a1af0a1e1dc.jpg',
    hoverImage: 'https://en.dermaline.co.kr/web/upload/category/editor/2024/12/02/9525cceae1c70e30eb49a888bdf218cf.jpg',
    tag: 'NEW',
    badgeTag: 'NEW',
    discountBadge: 'SAVE 78%',
    inStock: true,
    isBest: true,
    isEvent: true,
    isSpecialty: true,
  },
  {
    id: 'p-2',
    name: "D'LEXO Tension Master Real Lifting Ampoule 35ml",
    subtitle: 'High-Purity Bio-Lifting Peptide Solution',
    subTitle: 'High-Purity Bio-Lifting Peptide Solution',
    slug: 'dlexo-tension-master-lifting-ampoule',
    category: 'AMPOULE',
    line: 'Ampoule Care',
    lineSlug: 'ampoule-care',
    type: 'Ampoule/Essence',
    typeSlug: 'ampoule-essence',
    brand: 'DLEXO',
    brandSlug: 'dlexo',
    concern: 'Anti-Aging & Elasticity',
    price: 38.5,
    originalPrice: 45.0,
    rating: 4.9,
    reviewCount: 86,
    reviewsCount: 86,
    image: 'https://en.dermaline.co.kr/web/upload/category/editor/2024/12/02/9525cceae1c70e30eb49a888bdf218cf.jpg',
    hoverImage: 'https://en.dermaline.co.kr/web/upload/category/editor/2024/12/02/9f3e225d8efe11d4977e6a1af0a1e1dc.jpg',
    tag: 'NEW',
    badgeTag: 'NEW',
    discountBadge: 'SAVE 14%',
    inStock: true,
    isBest: true,
    isEvent: false,
    isSpecialty: false,
  },
  {
    id: 'p-3',
    name: "D'LEXO Exo-Peptide Bio-Booster Solution 50ml",
    subtitle: '10 Billion Plant Exosome Cellular Complex',
    subTitle: '10 Billion Plant Exosome Cellular Complex',
    slug: 'dlexo-exo-peptide-bio-booster',
    category: 'EXOSOME CARE',
    line: 'PDRN Care',
    lineSlug: 'pdrn-care',
    type: 'Special Ampoule',
    typeSlug: 'special-ampoule',
    brand: 'DLEXO',
    brandSlug: 'dlexo',
    concern: 'Moisture Barrier',
    price: 54.0,
    originalPrice: 65.0,
    rating: 5.0,
    reviewCount: 210,
    reviewsCount: 210,
    image: 'https://en.dermaline.co.kr/web/upload/category/editor/2024/12/02/7cf511574fe469cd67cd938c532abd20.jpg',
    hoverImage: 'https://en.dermaline.co.kr/web/upload/category/editor/2024/12/02/9f3e225d8efe11d4977e6a1af0a1e1dc.jpg',
    tag: 'BEST SELLER',
    badgeTag: 'BEST SELLER',
    discountBadge: 'SAVE 17%',
    inStock: true,
    isBest: true,
    isEvent: true,
    isSpecialty: true,
  },
  // 2. DERMALINE Hospital Line
  {
    id: 'p-4',
    name: 'PDX5 Skin Booster Total Solution 5ml*5vial',
    subtitle: 'Improvement of elasticity + Barrier Reinforcement',
    subTitle: 'Improvement of elasticity + Barrier Reinforcement',
    slug: 'pdx5-skin-booster-total-solution',
    category: 'PDRN CARE',
    line: 'PDRN Care',
    lineSlug: 'pdrn-care',
    type: 'Special Ampoule',
    typeSlug: 'special-ampoule',
    brand: 'DERMALINE',
    brandSlug: 'dermaline',
    concern: 'Moisture Barrier',
    price: 179.71,
    originalPrice: 240.0,
    rating: 5.0,
    reviewCount: 94,
    reviewsCount: 94,
    image: 'https://en.dermaline.co.kr/web/product/big/202603/7a7bef14e32eecfd07cd0508b6be29f5.jpg',
    hoverImage: 'https://en.dermaline.co.kr/web/product/big/202606/3a5b6c05e37530bd4f1ffbcd888ec38d.jpg',
    tag: 'CLINIC FAVORITE',
    badgeTag: 'CLINIC FAVORITE',
    discountBadge: 'SAVE 25%',
    inStock: true,
    isBest: true,
    isEvent: true,
    isSpecialty: true,
  },
  {
    id: 'p-5',
    name: 'Derma Solution PDRN Magic Ampoule 5ml*7ea',
    subtitle: 'High-Purified Salmon PDRN Tissue Regenerator',
    subTitle: 'High-Purified Salmon PDRN Tissue Regenerator',
    slug: 'derma-solution-pdrn-magic-ampoule',
    category: 'PDRN CARE',
    line: 'PDRN Care',
    lineSlug: 'pdrn-care',
    type: 'Ampoule/Essence',
    typeSlug: 'ampoule-essence',
    brand: 'DERMALINE',
    brandSlug: 'dermaline',
    concern: 'Sensitive & Soothing',
    price: 108.7,
    originalPrice: 150.0,
    rating: 4.8,
    reviewCount: 156,
    reviewsCount: 156,
    image: 'https://en.dermaline.co.kr/web/product/big/202606/3a5b6c05e37530bd4f1ffbcd888ec38d.jpg',
    hoverImage: 'https://en.dermaline.co.kr/web/product/big/202603/7a7bef14e32eecfd07cd0508b6be29f5.jpg',
    tag: 'BEST SELLER',
    badgeTag: 'BEST SELLER',
    discountBadge: 'SAVE 28%',
    inStock: true,
    isBest: true,
    isEvent: false,
    isSpecialty: true,
  },
  // 3. Cleansing & Trouble Care Line
  {
    id: 'p-6',
    name: 'Dermaline Gentle Cleansing Gel Fluid 1000ml',
    subtitle: 'Hypoallergenic Deep Pore Cleansing Foam',
    subTitle: 'Hypoallergenic Deep Pore Cleansing Foam',
    slug: 'dermaline-gentle-cleansing-gel-fluid',
    category: 'CLEANSING',
    line: 'Cleansing',
    lineSlug: 'cleansing',
    type: 'Cleansing',
    typeSlug: 'cleansing',
    brand: 'DERMALINE',
    brandSlug: 'dermaline',
    concern: 'Acne & Blemish',
    price: 42.0,
    originalPrice: 55.0,
    rating: 4.9,
    reviewCount: 78,
    reviewsCount: 78,
    image: 'https://en.dermaline.co.kr/web/product/big/202603/7a7bef14e32eecfd07cd0508b6be29f5.jpg',
    hoverImage: 'https://en.dermaline.co.kr/web/upload/category/editor/2024/12/02/9f3e225d8efe11d4977e6a1af0a1e1dc.jpg',
    tag: 'NEW',
    badgeTag: 'NEW',
    discountBadge: 'SAVE 24%',
    inStock: true,
    isBest: false,
    isEvent: true,
    isSpecialty: false,
  },
  {
    id: 'p-7',
    name: 'Dermaline AC Trouble Control Solution Spot Gel 30ml',
    subtitle: 'Calming Acne Spot Clarifying Gel',
    subTitle: 'Calming Acne Spot Clarifying Gel',
    slug: 'dermaline-ac-trouble-spot-gel',
    category: 'SOLUTION',
    line: 'Trouble Care',
    lineSlug: 'trouble-care',
    type: 'Cream/Eye Cream',
    typeSlug: 'cream-eye-cream',
    brand: 'DERMALINE',
    brandSlug: 'dermaline',
    concern: 'Acne & Blemish',
    price: 28.5,
    originalPrice: 38.0,
    rating: 4.7,
    reviewCount: 64,
    reviewsCount: 64,
    image: 'https://en.dermaline.co.kr/web/upload/category/editor/2024/12/02/7cf511574fe469cd67cd938c532abd20.jpg',
    hoverImage: 'https://en.dermaline.co.kr/web/upload/category/editor/2024/12/02/9525cceae1c70e30eb49a888bdf218cf.jpg',
    tag: 'HOT',
    badgeTag: 'HOT',
    discountBadge: 'SAVE 25%',
    inStock: true,
    isBest: false,
    isEvent: true,
    isSpecialty: false,
  },
  // 4. Sun Care & Hydration Line
  {
    id: 'p-8',
    name: 'Dermaline Bio UV Shield Perfect Sun Cream SPF50+ PA++++',
    subtitle: 'Non-Greasy Clinical Sunscreen 50ml',
    subTitle: 'Non-Greasy Clinical Sunscreen 50ml',
    slug: 'dermaline-bio-uv-shield-sun-cream',
    category: 'SOLUTION',
    line: 'Sun Care',
    lineSlug: 'sun-care',
    type: 'Sun Care/BB',
    typeSlug: 'sun-care-bb',
    brand: 'DERMALINE',
    brandSlug: 'dermaline',
    concern: 'UV Protection',
    price: 32.0,
    originalPrice: 40.0,
    rating: 4.9,
    reviewCount: 142,
    reviewsCount: 142,
    image: 'https://en.dermaline.co.kr/web/upload/category/editor/2024/12/02/9f3e225d8efe11d4977e6a1af0a1e1dc.jpg',
    hoverImage: 'https://en.dermaline.co.kr/web/upload/category/editor/2024/12/02/7cf511574fe469cd67cd938c532abd20.jpg',
    tag: 'BEST SELLER',
    badgeTag: 'BEST SELLER',
    discountBadge: 'SAVE 20%',
    inStock: true,
    isBest: true,
    isEvent: false,
    isSpecialty: false,
  },
  {
    id: 'p-9',
    name: 'r:Eden Hyaluronic Aqua Balance Toner 500ml',
    subtitle: '8-Layer Hydration Moisture Balancing Toner',
    subTitle: '8-Layer Hydration Moisture Balancing Toner',
    slug: 'reden-hyaluronic-aqua-toner',
    category: 'SOLUTION',
    line: 'Oil/Moisture Balancing',
    lineSlug: 'oil-moisture-balancing',
    type: 'Toner/Mist',
    typeSlug: 'toner-mist',
    brand: 'R:EDEN',
    brandSlug: 'reden',
    concern: 'Moisture Barrier',
    price: 34.0,
    originalPrice: 48.0,
    rating: 4.8,
    reviewCount: 92,
    reviewsCount: 92,
    image: 'https://en.dermaline.co.kr/web/product/big/202606/3a5b6c05e37530bd4f1ffbcd888ec38d.jpg',
    hoverImage: 'https://en.dermaline.co.kr/web/product/big/202603/7a7bef14e32eecfd07cd0508b6be29f5.jpg',
    tag: 'NEW',
    badgeTag: 'NEW',
    discountBadge: 'SAVE 29%',
    inStock: true,
    isBest: false,
    isEvent: true,
    isSpecialty: false,
  },
  {
    id: 'p-10',
    name: 'r:Eden Ceramide Barrier Intensive Emulsion 200ml',
    subtitle: 'Nourishing Lipid Emulsion Lotion',
    subTitle: 'Nourishing Lipid Emulsion Lotion',
    slug: 'reden-ceramide-barrier-emulsion',
    category: 'SOLUTION',
    line: 'Oil/Moisture Balancing',
    lineSlug: 'oil-moisture-balancing',
    type: 'Lotion/Emulsion',
    typeSlug: 'lotion-emulsion',
    brand: 'R:EDEN',
    brandSlug: 'reden',
    concern: 'Moisture Barrier',
    price: 38.0,
    originalPrice: 50.0,
    rating: 4.9,
    reviewCount: 75,
    reviewsCount: 75,
    image: 'https://en.dermaline.co.kr/web/upload/category/editor/2024/12/02/9525cceae1c70e30eb49a888bdf218cf.jpg',
    hoverImage: 'https://en.dermaline.co.kr/web/upload/category/editor/2024/12/02/9f3e225d8efe11d4977e6a1af0a1e1dc.jpg',
    tag: 'NEW',
    badgeTag: 'NEW',
    discountBadge: 'SAVE 24%',
    inStock: true,
    isBest: false,
    isEvent: false,
    isSpecialty: false,
  },
  // 5. Masks & Specialty Sets
  {
    id: 'p-11',
    name: 'r:Eden Cooling Hydrogel Modeling Mask Set 500g',
    subtitle: 'Professional Clinic Modeling Mask Pack',
    subTitle: 'Professional Clinic Modeling Mask Pack',
    slug: 'reden-cooling-hydrogel-modeling-mask',
    category: 'EXOSOME CARE',
    line: 'Keratin Care',
    lineSlug: 'keratin-care',
    type: 'Modeling Mask Pack',
    typeSlug: 'modeling-mask-pack',
    brand: 'R:EDEN',
    brandSlug: 'reden',
    concern: 'Skin Texture',
    price: 45.0,
    originalPrice: 60.0,
    rating: 5.0,
    reviewCount: 110,
    reviewsCount: 110,
    image: 'https://en.dermaline.co.kr/web/upload/category/editor/2024/12/02/7cf511574fe469cd67cd938c532abd20.jpg',
    hoverImage: 'https://en.dermaline.co.kr/web/upload/category/editor/2024/12/02/9525cceae1c70e30eb49a888bdf218cf.jpg',
    tag: 'CLINIC FAVORITE',
    badgeTag: 'CLINIC FAVORITE',
    discountBadge: 'SAVE 25%',
    inStock: true,
    isBest: true,
    isEvent: true,
    isSpecialty: true,
  },
  {
    id: 'p-12',
    name: 'Dermaline PDRN Cell Renewal Mask Sheet (10 Sheets)',
    subtitle: '100% Cotton Bio Sheet Mask Pack',
    subTitle: '100% Cotton Bio Sheet Mask Pack',
    slug: 'dermaline-pdrn-cell-mask-pack',
    category: 'PDRN CARE',
    line: 'PDRN Care',
    lineSlug: 'pdrn-care',
    type: 'Mask Pack',
    typeSlug: 'mask-pack',
    brand: 'DERMALINE',
    brandSlug: 'dermaline',
    concern: 'Sensitive & Soothing',
    price: 35.0,
    originalPrice: 48.0,
    rating: 4.8,
    reviewCount: 135,
    reviewsCount: 135,
    image: 'https://en.dermaline.co.kr/web/product/big/202603/7a7bef14e32eecfd07cd0508b6be29f5.jpg',
    hoverImage: 'https://en.dermaline.co.kr/web/product/big/202606/3a5b6c05e37530bd4f1ffbcd888ec38d.jpg',
    tag: 'BEST SELLER',
    badgeTag: 'BEST SELLER',
    discountBadge: 'SAVE 27%',
    inStock: true,
    isBest: true,
    isEvent: false,
    isSpecialty: false,
  },
  {
    id: 'p-13',
    name: 'Dermaline Royal Clinical Complete Skincare SET (4 Items)',
    subtitle: 'Toner + Emulsion + Ampoule + Cream Full Set',
    subTitle: 'Toner + Emulsion + Ampoule + Cream Full Set',
    slug: 'dermaline-royal-clinical-set',
    category: 'SPECIAL AMPOULE',
    line: 'Special Ampoule Care',
    lineSlug: 'special-ampoule-care',
    type: 'SET',
    typeSlug: 'set',
    brand: 'DERMALINE',
    brandSlug: 'dermaline',
    concern: 'Anti-Aging & Elasticity',
    price: 198.0,
    originalPrice: 280.0,
    rating: 5.0,
    reviewCount: 68,
    reviewsCount: 68,
    image: 'https://en.dermaline.co.kr/web/upload/category/editor/2024/12/02/9f3e225d8efe11d4977e6a1af0a1e1dc.jpg',
    hoverImage: 'https://en.dermaline.co.kr/web/upload/category/editor/2024/12/02/7cf511574fe469cd67cd938c532abd20.jpg',
    tag: 'SPECIAL SET',
    badgeTag: 'SPECIAL SET',
    discountBadge: 'SAVE 29%',
    inStock: true,
    isBest: true,
    isEvent: true,
    isSpecialty: true,
  },
];

export const MOCK_PRODUCTS_DATA = MOCK_PRODUCTS;
