import { HomeDataModel } from './models/home.model';

export const mockHomeData: HomeDataModel = {
  hero: {
    badge: '100% KOREAN DERMA SKINCARE',
    titlePart1: 'REDESIGNING THE STANDARD OF',
    titlePart2: 'MEDICAL AESTHETICS',
    description:
      'Engineered with pure biocompatible polymers and bio-active cellular peptides. DERMALINE delivers hospital-proven clinical efficacy for skin reconstruction.',
    primaryCtaText: 'SHOP ALL SKINCARE',
    secondaryCtaText: 'EXPLORE BEST SELLERS',
    bgImage: '/images/hero/hero_korean_model_1.jpg',
    slides: [
      {
        id: 1,
        badge: 'BIO-PDRN 99.5% PURITY • BESTSELLING SERUM',
        titlePart1: 'SALMON PDRN ADVANCED',
        titlePart2: 'RECOVERY AMPOULE SERUM',
        description:
          'Infused with 99.5% pure salmon DNA PDRN and hyaluronic acid. Deeply hydrates, activates collagen production, and restores skin barrier resilience.',
        primaryCtaText: 'SHOP PDRN SERUM',
        primaryCtaLink: '/products',
        secondaryCtaText: 'SEE INGREDIENTS',
        secondaryCtaLink: '/brand/story',
        productImage: '/images/hero/hero_korean_model_1.jpg',
        bgGradient: 'from-white via-sky-50/40 to-slate-50',
        floatingBadge: '99.5% Salmon PDRN • Dermatologist Tested',
        productSpecsTitle: 'PDRN SERUM KEY BENEFITS',
        productSpecs: [
          { label: 'Key Active', value: 'High-Purity Salmon PDRN (5,000 ppm)' },
          { label: 'Hydration', value: '8-Layer Hyaluronic Acid Complex' },
          { label: 'Skin Type', value: 'All Skin Types (Hypoallergenic 0.0%)' },
          { label: 'Volume', value: '35ml / 1.18 fl. oz.' },
        ],
        stats: [
          { value: '99.5%', label: 'PDRN Active Purity' },
          { value: '2.4x', label: 'Faster Skin Renewal' },
          { value: '100%', label: 'Dermatologist Approved' },
        ],
      },
      {
        id: 2,
        badge: 'BARRIER REPAIR • INTENSIVE CARE',
        titlePart1: 'EXO-PEPTIDE INTENSIVE',
        titlePart2: 'BARRIER RECOVERY CREAM',
        description:
          'Enriched with 10 Billion exosome nanospheres and 5 ceramide types. Strengthens damaged skin barrier, locks in moisture, and calms redness.',
        primaryCtaText: 'SHOP RECOVERY CREAM',
        primaryCtaLink: '/products',
        secondaryCtaText: 'VIEW BENEFITS',
        secondaryCtaLink: '/brand/story',
        productImage: '/images/hero/hero_korean_model_2.jpg',
        bgGradient: 'from-white via-sky-50/50 to-blue-50/30',
        floatingBadge: '10 Billion Exosomes • Deep Barrier Repair',
        productSpecsTitle: 'RECOVERY CREAM KEY BENEFITS',
        productSpecs: [
          { label: 'Key Active', value: 'Plant Exosomes & 5-Ceramide Blend' },
          { label: 'Texture', value: 'Rich Velvet Meltdown Cream' },
          { label: 'Skin Benefit', value: 'Instant Soothing & Barrier Lock' },
          { label: 'Volume', value: '100g / 3.52 oz.' },
        ],
        stats: [
          { value: '10B+', label: 'Active Exosomes' },
          { value: '72h', label: 'Moisture Retention' },
          { value: '0.0%', label: 'Irritation Score' },
        ],
      },
      {
        id: 3,
        badge: 'GLOW & HYDRATION • TREATMENT MASK',
        titlePart1: 'COLLAGEN BIO-CELLULOSE',
        titlePart2: 'DEEP HYDRATING MASK SET',
        description:
          'Ultra-fitting bio-cellulose sheet mask drenched in marine collagen and niacinamide. Provides immediate glass-skin luminosity and plumpness.',
        primaryCtaText: 'SHOP SHEET MASKS',
        primaryCtaLink: '/products',
        secondaryCtaText: 'EXPLORE SETS',
        secondaryCtaLink: '/products',
        productImage: '/images/hero/hero_korean_model_3.jpg',
        bgGradient: 'from-white via-indigo-50/40 to-sky-50',
        floatingBadge: 'Hydro-Gel Sheet • Glass Skin Glow',
        productSpecsTitle: 'SHEET MASK KEY BENEFITS',
        productSpecs: [
          { label: 'Key Active', value: 'Hydrolyzed Marine Collagen' },
          { label: 'Sheet Material', value: '100% Natural Coconut Bio-Cellulose' },
          { label: 'Effect', value: 'Instant Plumping & Brightening' },
          { label: 'Quantity', value: 'Box of 10 Sheets' },
        ],
        stats: [
          { value: '10x', label: 'Deeper Essence Intake' },
          { value: '15 min', label: 'Instant Glow Boost' },
          { value: '100%', label: 'Vegan Biodegradable' },
        ],
      },
    ],
  },
  about: {
    eyebrow: 'DERMACOSMETICS FOR SKIN RECOVERY',
    title: 'About DERMALINE',
    paragraph1:
      'Dermaline constantly agonized and studied to improve fundamental skin concerns.',
    paragraph2:
      'Based on the time and effort accumulated by developing skin care products at hospitals for many years, I promise to take the lead as a dermatology brand that provides solutions for healthy skin.',
    tagline: 'DERMACOSMETICS FOR SKIN RECOVERY',
    titleLine1: 'About DERMALINE',
    titleLine2: 'Fundamental Skincare Solutions',
    description:
      'Dermaline constantly agonized and studied to improve fundamental skin concerns. Based on the time and effort accumulated by developing skin care products at hospitals for many years, I promise to take the lead as a dermatology brand that provides solutions for healthy skin.',
    bannerImage: '/images/about/about_derma_lab.jpg',
    floatingQuoteTitle: 'SOLUTION FOR HEALTHY SKIN',
    floatingQuoteDesc: 'Years of hospital skincare R&D providing fundamental solutions for healthy skin.',
    statistics: [
      { value: '15+', label: 'Years Hospital Skincare R&D' },
      { value: '99.8%', label: 'Active Purity Standard' },
      { value: '100%', label: 'Dermatologist Approved' },
    ],
    features: [
      {
        title: 'Hospital-Proven Science',
        desc: 'Formulated based on years of hospital skincare development to solve core skin concerns.',
        badge: 'CLINICAL R&D',
      },
      {
        title: 'Fundamental Skin Recovery',
        desc: 'Targeting root cause skin concerns to restore natural dermal resilience and health.',
        badge: 'HEALTHY SKIN',
      },
    ],
  },
  innovators: [
    {
      id: 1,
      title: "D'LEXO NAD Power Solution Ampoule 35ml",
      category: 'Ampoule & Solution',
      badge: 'USA COSTCO BESTSELLER',
      badgeVariant: 'gold',
      description: 'High-performance NAD anti-aging solution ampoule formulation available at USA Costco for intensive cellular revival.',
      image: 'https://en.dermaline.co.kr/web/product/big/202603/7a7bef14e32eecfd07cd0508b6be29f5.jpg',
    },
    {
      id: 2,
      title: "D'LEXO NAD Power Solution Bubble Toner 200ml",
      category: 'Toner & Cleansing',
      badge: 'USA COSTCO SELECTION',
      badgeVariant: 'primary',
      description: 'Rich micro-bubble oxygenating toner delivering rapid hydration and deep dermal nutrient absorption.',
      image: 'https://en.dermaline.co.kr/web/product/big/202606/3a5b6c05e37530bd4f1ffbcd888ec38d.jpg',
    },
    {
      id: 3,
      title: "D'LEXO Collagen Gel Cream 100g",
      category: 'Moisturizer & Gel Cream',
      badge: 'COLLAGEN GLOW',
      badgeVariant: 'dark',
      description: 'Plumping hydrolyzed marine collagen gel cream restoring elastic firmness and glass-skin radiance.',
      image: 'https://en.dermaline.co.kr/web/product/big/202507/108768d37af6cdd1c938d9e67c19ea1b.jpg',
    },
  ],
  products: [
    {
      id: 101,
      name: "D'LEXO NAD Power Solution Ampoule 35ml",
      category: 'Ampoule & Solution',
      price: '$35.21',
      originalPrice: '$42.00',
      tag: 'NEW',
      image: 'https://en.dermaline.co.kr/web/product/big/202603/7a7bef14e32eecfd07cd0508b6be29f5.jpg',
    },
    {
      id: 102,
      name: "D'LEXO NAD Power Solution Bubble Toner 200ml",
      category: 'Toner & Cleansing',
      price: '$38.73',
      originalPrice: '$45.00',
      tag: 'NEW',
      image: 'https://en.dermaline.co.kr/web/product/big/202606/3a5b6c05e37530bd4f1ffbcd888ec38d.jpg',
    },
    {
      id: 103,
      name: "D'LEXO NAD Power Solution Cream 100ml",
      category: 'Moisturizer & Cream',
      price: '$45.77',
      originalPrice: '$52.00',
      tag: 'NEW',
      image: 'https://en.dermaline.co.kr/web/product/big/202603/588a7ed96748db6f756ab51b451d0019.jpg',
    },
    {
      id: 104,
      name: "D'LEXO Collagen Gel Cream 100g",
      category: 'Moisturizer & Gel Cream',
      price: '$45.65',
      originalPrice: '$50.00',
      tag: 'NEW',
      image: 'https://en.dermaline.co.kr/web/product/big/202507/108768d37af6cdd1c938d9e67c19ea1b.jpg',
    },
    {
      id: 105,
      name: "D'LEXO Cica Exo Composing Toner 200ml",
      category: 'Soothing & Toner',
      price: '$32.50',
      tag: 'NEW',
      image: 'https://en.dermaline.co.kr/web/upload/category/editor/2024/12/02/079dd8271e254aaebd582633c48049c5.jpg',
    },
    {
      id: 106,
      name: "D'LEXO Aqua Vita Solution Cream 100g",
      category: 'Hydrating Cream',
      price: '$42.00',
      originalPrice: '$48.00',
      tag: 'NEW',
      image: 'https://en.dermaline.co.kr/web/upload/category/editor/2024/12/02/7cf511574fe469cd67cd938c532abd20.jpg',
    },
    {
      id: 107,
      name: 'PDRN Solution Salmon Ampoule 35ml',
      category: 'Cellular Bio-Booster',
      price: '$48.00',
      originalPrice: '$55.00',
      tag: 'NEW',
      image: 'https://en.dermaline.co.kr/web/upload/category/editor/2024/12/02/9f3e225d8efe11d4977e6a1af0a1e1dc.jpg',
    },
    {
      id: 108,
      name: 'Bio-Cellulose Deep Hydrating Mask Box (10 Sheets)',
      category: 'Mask & Treatment',
      price: '$35.00',
      tag: 'NEW',
      image: '/images/hero/hero_studio_3.jpg',
    },
    {
      id: 109,
      name: 'Exo-Peptide Barrier Recovery Cream 80ml',
      category: 'Barrier Care',
      price: '$52.00',
      originalPrice: '$60.00',
      tag: 'NEW',
      image: '/images/hero/hero_studio_1.jpg',
    },
  ],
  recommendations: [
    {
      id: 'special-ampoule',
      tag: '# Special ampoule',
      label: 'Special Ampoule Series',
      subtitle: 'Targeted hospital-grade clinical boosters for intense dermal regeneration.',
      products: [
        {
          id: 201,
          name: "D'LEXO Collagen Sil Booster Ampoule 70mg*4ea+35ml",
          subTitle: 'PDRN Solution Collagen Booster Ampoule 35ml',
          categoryTag: 'SPECIAL AMPOULE',
          price: 'USD 36.23',
          originalPrice: 'USD 172.46',
          discountBadge: 'SAVE 78%',
          image: 'https://en.dermaline.co.kr/web/upload/category/editor/2024/12/02/9f3e225d8efe11d4977e6a1af0a1e1dc.jpg',
          rating: 4.9,
          reviewsCount: 128,
          stepBadge: 'STEP 01 • BOOSTER',
        },
        {
          id: 202,
          name: 'PDX5 Skin Booster Total Solution 5ml*5vial',
          subTitle: 'Improvement of elasticity + Barrier Reinforcement',
          categoryTag: 'SKIN BOOSTER',
          price: 'USD 179.71',
          originalPrice: 'USD 240.00',
          discountBadge: 'SAVE 25%',
          image: 'https://en.dermaline.co.kr/web/product/big/202603/7a7bef14e32eecfd07cd0508b6be29f5.jpg',
          rating: 5.0,
          reviewsCount: 94,
          stepBadge: 'STEP 02 • TOTAL CARE',
        },
        {
          id: 203,
          name: 'Derma Solution PDRN Magic Ampoule 5ml*7ea',
          subTitle: 'Derma Solution PDRN Magic Ampoule 5ml*7ea',
          categoryTag: 'PDRN MAGIC',
          price: 'USD 108.70',
          originalPrice: 'USD 150.00',
          discountBadge: 'SAVE 28%',
          image: 'https://en.dermaline.co.kr/web/product/big/202606/3a5b6c05e37530bd4f1ffbcd888ec38d.jpg',
          rating: 4.8,
          reviewsCount: 156,
          stepBadge: 'STEP 03 • REGENERATION',
        },
      ],
    },
    {
      id: 'ampoule',
      tag: '# Ampoule',
      label: 'Concentrated Cellular Ampoules',
      subtitle: 'Pure active serums formulated with high-potency bio-peptides.',
      products: [
        {
          id: 204,
          name: "D'LEXO NAD Power Solution Ampoule 35ml",
          subTitle: 'High-purity cellular NAD anti-aging solution',
          categoryTag: 'NAD AMPOULE',
          price: 'USD 35.21',
          originalPrice: 'USD 42.00',
          discountBadge: 'SAVE 16%',
          image: 'https://en.dermaline.co.kr/web/product/big/202603/7a7bef14e32eecfd07cd0508b6be29f5.jpg',
          rating: 4.9,
          reviewsCount: 210,
          stepBadge: 'STEP 01 • NAD CELLULAR',
        },
        {
          id: 205,
          name: 'PDRN Solution Salmon Ampoule 35ml',
          subTitle: '99.5% Pure Salmon DNA skin renewal ampoule',
          categoryTag: 'SALMON PDRN',
          price: 'USD 48.00',
          originalPrice: 'USD 58.00',
          discountBadge: 'SAVE 17%',
          image: 'https://en.dermaline.co.kr/web/upload/category/editor/2024/12/02/9f3e225d8efe11d4977e6a1af0a1e1dc.jpg',
          rating: 5.0,
          reviewsCount: 340,
          stepBadge: 'STEP 02 • SALMON PDRN',
        },
        {
          id: 206,
          name: 'Exo-Peptide Bio Repair Ampoule 50ml',
          subTitle: '10 Billion plant exosomes for barrier recovery',
          categoryTag: 'EXOSOME REPAIR',
          price: 'USD 55.00',
          originalPrice: 'USD 68.00',
          discountBadge: 'SAVE 19%',
          image: 'https://en.dermaline.co.kr/web/product/big/202507/108768d37af6cdd1c938d9e67c19ea1b.jpg',
          rating: 4.9,
          reviewsCount: 88,
          stepBadge: 'STEP 03 • EXOSOME REPAIR',
        },
      ],
    },
    {
      id: 'toner-emulsion',
      tag: '# Toner / Emulsion',
      label: 'Hydrating Toners & Emulsions',
      subtitle: 'Oxygenating micro-bubble toners and dermal balance emulsions.',
      products: [
        {
          id: 207,
          name: "D'LEXO NAD Power Solution Bubble Toner 200ml",
          subTitle: 'Oxygenating micro-bubble skin balancing toner',
          categoryTag: 'BUBBLE TONER',
          price: 'USD 38.73',
          originalPrice: 'USD 46.00',
          discountBadge: 'SAVE 15%',
          image: 'https://en.dermaline.co.kr/web/product/big/202606/3a5b6c05e37530bd4f1ffbcd888ec38d.jpg',
          rating: 4.8,
          reviewsCount: 175,
          stepBadge: 'STEP 01 • OXYGEN BUBBLE',
        },
        {
          id: 208,
          name: "D'LEXO Cica Exo Composing Toner 200ml",
          subTitle: 'Soothing Centella Asiatica & Exosome toner',
          categoryTag: 'CICA TONER',
          price: 'USD 32.50',
          originalPrice: 'USD 40.00',
          discountBadge: 'SAVE 18%',
          image: 'https://en.dermaline.co.kr/web/upload/category/editor/2024/12/02/079dd8271e254aaebd582633c48049c5.jpg',
          rating: 4.9,
          reviewsCount: 142,
          stepBadge: 'STEP 02 • CICA SOOTHING',
        },
        {
          id: 209,
          name: 'Bio-Balance Hydrating Emulsion 150ml',
          subTitle: 'Lightweight lipid emulsion for continuous barrier lock',
          categoryTag: 'EMULSION',
          price: 'USD 36.00',
          originalPrice: 'USD 45.00',
          discountBadge: 'SAVE 20%',
          image: '/images/hero/hero_studio_2.jpg',
          rating: 4.7,
          reviewsCount: 96,
          stepBadge: 'STEP 03 • EMULSION LOCK',
        },
      ],
    },
    {
      id: 'mask-pack',
      tag: '# Mask pack',
      label: 'Bio-Cellulose Treatment Masks',
      subtitle: 'Ultra-fitting coconut bio-cellulose sheet masks for instant glass-skin radiance.',
      products: [
        {
          id: 210,
          name: 'Bio-Cellulose Deep Hydrating Mask Box (10 Sheets)',
          subTitle: 'Hydro-gel coconut sheet soaked in marine collagen essence',
          categoryTag: 'SHEET MASK SET',
          price: 'USD 35.00',
          originalPrice: 'USD 45.00',
          discountBadge: 'SAVE 22%',
          image: '/images/hero/hero_studio_3.jpg',
          rating: 5.0,
          reviewsCount: 412,
          stepBadge: 'STEP 01 • DEEP HYDRATION',
        },
        {
          id: 211,
          name: 'PDRN Intensive Rejuvenating Sheet Mask Box',
          subTitle: 'Salmon DNA PDRN post-treatment soothing mask',
          categoryTag: 'PDRN MASK',
          price: 'USD 42.00',
          originalPrice: 'USD 52.00',
          discountBadge: 'SAVE 19%',
          image: '/images/hero/hero_studio_1.jpg',
          rating: 4.9,
          reviewsCount: 290,
          stepBadge: 'STEP 02 • REPAIR MASK',
        },
        {
          id: 212,
          name: 'Cooling Cica Calming Hydrogel Mask (5 Sheets)',
          subTitle: 'Instant cooling temperature reduction hydrogel mask',
          categoryTag: 'COOLING MASK',
          price: 'USD 28.00',
          originalPrice: 'USD 35.00',
          discountBadge: 'SAVE 20%',
          image: '/images/about/about_derma_lab.jpg',
          rating: 4.8,
          reviewsCount: 164,
          stepBadge: 'STEP 03 • COOLING MASK',
        },
      ],
    },
    {
      id: 'cream',
      tag: '# Cream',
      label: 'Dermal Moisture & Repair Creams',
      subtitle: 'Rich cellular creams locking in active nutrients and building barrier resilience.',
      products: [
        {
          id: 213,
          name: "D'LEXO NAD Power Solution Cream 100ml",
          subTitle: 'Anti-aging NAD cellular power cream for deep dermal elasticity',
          categoryTag: 'NAD CREAM',
          price: 'USD 45.77',
          originalPrice: 'USD 55.00',
          discountBadge: 'SAVE 16%',
          image: 'https://en.dermaline.co.kr/web/product/big/202603/588a7ed96748db6f756ab51b451d0019.jpg',
          rating: 4.9,
          reviewsCount: 250,
          stepBadge: 'STEP 01 • INTENSIVE CREAM',
        },
        {
          id: 214,
          name: "D'LEXO Collagen Gel Cream 100g",
          subTitle: 'Hydrolyzed marine collagen gel cream for bouncy glass glow',
          categoryTag: 'COLLAGEN GEL',
          price: 'USD 45.65',
          originalPrice: 'USD 58.00',
          discountBadge: 'SAVE 21%',
          image: 'https://en.dermaline.co.kr/web/product/big/202507/108768d37af6cdd1c938d9e67c19ea1b.jpg',
          rating: 5.0,
          reviewsCount: 380,
          stepBadge: 'STEP 02 • COLLAGEN GEL',
        },
        {
          id: 215,
          name: "D'LEXO Aqua Vita Solution Cream 100g",
          subTitle: 'Multivitamin water-drop gel cream for luminous skin tone',
          categoryTag: 'AQUA VITA',
          price: 'USD 42.00',
          originalPrice: 'USD 50.00',
          discountBadge: 'SAVE 16%',
          image: 'https://en.dermaline.co.kr/web/upload/category/editor/2024/12/02/7cf511574fe469cd67cd938c532abd20.jpg',
          rating: 4.8,
          reviewsCount: 185,
          stepBadge: 'STEP 03 • AQUA VITA',
        },
      ],
    },
  ],
};

export const MOCK_HOME_DATA = mockHomeData;
